language: java

install: /bin/true

jdk:
- openjdk6
- oraclejdk7
- oraclejdk8

before_install:
 - chmod +x gradlew


before_script:
    - wget https://services.gradle.org/distributions/gradle-4.2-bin.zip
    - unzip gradle-4.2-bin.zip
    - export GRADLE_HOME=$PWD/gradle-4.2
    - export PATH=$GRADLE_HOME/bin:$PATH


script:
- ./gradlew assemble
- ./gradlew check
- ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
